# Generated by Django 4.0.4 on 2022-05-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questiana_record',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Object', models.CharField(max_length=250, null=True)),
                ('Cleaned_obj_not', models.CharField(max_length=250, null=True)),
                ('Tetenus', models.CharField(max_length=250, null=True)),
                ('Caused_obj_Clean_not', models.CharField(max_length=250, null=True)),
                ('Reaction', models.CharField(max_length=250, null=True)),
                ('Alurgies', models.CharField(max_length=250, null=True)),
                ('Patient_Id', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='questianb_record',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Object', models.CharField(max_length=250, null=True)),
                ('Cleaned_obj_not', models.CharField(max_length=250, null=True)),
                ('Tetenus', models.CharField(max_length=250, null=True)),
                ('Caused_obj_Clean_not', models.CharField(max_length=250, null=True)),
                ('Reaction', models.CharField(max_length=250, null=True)),
                ('Alurgies', models.CharField(max_length=250, null=True)),
                ('Patient_Id', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
