# Generated by Django 4.0.4 on 2022-05-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_questiana_record_questianb_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiana_record',
            old_name='Alurgies',
            new_name='q1',
        ),
        migrations.RenameField(
            model_name='questiana_record',
            old_name='Caused_obj_Clean_not',
            new_name='q2',
        ),
        migrations.RenameField(
            model_name='questiana_record',
            old_name='Cleaned_obj_not',
            new_name='q3',
        ),
        migrations.RenameField(
            model_name='questiana_record',
            old_name='Object',
            new_name='q4',
        ),
        migrations.RenameField(
            model_name='questiana_record',
            old_name='Reaction',
            new_name='q5',
        ),
        migrations.RenameField(
            model_name='questiana_record',
            old_name='Tetenus',
            new_name='q6',
        ),
        migrations.RenameField(
            model_name='questianb_record',
            old_name='Alurgies',
            new_name='q1',
        ),
        migrations.RenameField(
            model_name='questianb_record',
            old_name='Caused_obj_Clean_not',
            new_name='q2',
        ),
        migrations.RenameField(
            model_name='questianb_record',
            old_name='Cleaned_obj_not',
            new_name='q3',
        ),
        migrations.RenameField(
            model_name='questianb_record',
            old_name='Object',
            new_name='q4',
        ),
        migrations.RenameField(
            model_name='questianb_record',
            old_name='Reaction',
            new_name='q5',
        ),
        migrations.RenameField(
            model_name='questianb_record',
            old_name='Tetenus',
            new_name='q6',
        ),
        migrations.RemoveField(
            model_name='questiana_record',
            name='Patient_Id',
        ),
        migrations.RemoveField(
            model_name='questianb_record',
            name='Patient_Id',
        ),
        migrations.AddField(
            model_name='questiana_record',
            name='q7',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='questiana_record',
            name='q8',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='questiana_record',
            name='q9',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='questianb_record',
            name='q7',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='questianb_record',
            name='q8',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='questianb_record',
            name='q9',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
