# Generated by Django 4.0.4 on 2022-05-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_rename_alurgies_questiana_record_q1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiana_record',
            name='Patient_Id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questianb_record',
            name='Patient_Id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
