# Generated by Django 4.0.4 on 2022-05-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aknow',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250, null=True)),
                ('view', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('RegisterNumber', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=250, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Address', models.CharField(max_length=250)),
                ('Age', models.CharField(max_length=250, null=True)),
                ('Dob', models.CharField(max_length=250, null=True)),
                ('Phone', models.CharField(max_length=250, null=True)),
                ('Aadhar', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='messagesre',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Kid_Id', models.IntegerField(null=True)),
                ('vax_name', models.CharField(max_length=250, null=True)),
                ('value', models.CharField(max_length=250, null=True)),
                ('first_vax_date', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
